[package]
name = "goods"
version = "0.1.0"
authors = ["zakarumych"]
edition = "2018"
description = "Asset manager for good assets"
license = "MIT OR Apache-2.0"
documentation = "https://docs.rs/goods"
keywords = ["assets", "no_std", "async", "wasm", "web"]
repository = "https://github.com/zakarumych/goods"

[features]
std = []
fs = ["std"]

json-format = ["serde", "serde_json"]
yaml-format = ["serde", "serde_yaml"]
ron-format = ["serde", "ron"]

[dependencies]
futures-core = { version = "0.3", default-features = false, features = ["alloc"] }
spin = "0.5"
log = { version = "0.4", default-features = false }
pin-utils = { version = "0.1.0-alpha.4", default-features = false }
hashbrown = { version = "0.7" }

serde = { version = "1.0", optional = true, default-features = false, features = ["derive"] }
serde_json = { version = "1.0", optional = true, default-features = false, features = ["alloc"] }
serde_yaml = { version = "0.8", optional = true, default-features = false }
ron = { version = "0.5", optional = true, default-features = false }
reqwest = { version = "0.10", optional = true, default-features = false }

[dev-dependencies]
env_logger = "0.7"
thiserror = "1.0"
tokio = { version = "0.2", features = ["rt-core", "macros"] }
futures-task = { version = "0.3" }
legion = "0.2"

[[example]]
name = "fs"
required-features = ["fs", "json-format", "yaml-format"]

[[example]]
name = "reqwest"
required-features = ["reqwest", "json-format"]

[[example]]
name = "legion"
required-features = ["ron-format"]
